<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TourPackagesTableSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        $packages = [
            [
                'name' => 'Everest Panorama Trek',
                'description' => 'Classic trek with stunning views of Everest and surrounding peaks.',
                'trek_type' => 'scenic',
                'tags' => json_encode(['everest','himalaya','panorama']),
                'season' => json_encode(['spring','autumn']),
                'region' => 'Solukhumbu',
                'views_count' => 1200,
                'bookings_count' => 85,
                'rating_avg' => 4.85,
                'rating_count' => 40,
                'price' => 150000.00,
                'duration_days' => 12,
                'difficulty_level' => 'hard',
                'max_participants' => 12,
                'image' => 'https://images.unsplash.com/photo-1508264165352-cd3b6f0a2f2e?q=80&w=1200&auto=format&fit=crop',
                'start_location_name' => 'Lukla',
                'start_lat' => 27.6868,
                'start_lng' => 86.7294,
                'end_location_name' => 'Lukla',
                'end_lat' => 27.6868,
                'end_lng' => 86.7294,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Annapurna Base Camp Trek',
                'description' => 'A popular trek through rhododendron forests to Annapurna Base Camp.',
                'trek_type' => 'nature',
                'tags' => json_encode(['annapurna','forest','mountain']),
                'season' => json_encode(['spring','autumn']),
                'region' => 'Gandaki',
                'views_count' => 980,
                'bookings_count' => 60,
                'rating_avg' => 4.70,
                'rating_count' => 33,
                'price' => 90000.00,
                'duration_days' => 10,
                'difficulty_level' => 'moderate',
                'max_participants' => 15,
                'image' => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop',
                'start_location_name' => 'Pokhara',
                'start_lat' => 28.2096,
                'start_lng' => 83.9856,
                'end_location_name' => 'Pokhara',
                'end_lat' => 28.2096,
                'end_lng' => 83.9856,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Langtang Valley Trek',
                'description' => 'Experience Tamang villages and local culture in Langtang valley.',
                'trek_type' => 'cultural',
                'tags' => json_encode(['langtang','culture','valley']),
                'season' => json_encode(['spring','autumn','winter']),
                'region' => 'Bagmati',
                'views_count' => 420,
                'bookings_count' => 20,
                'rating_avg' => 4.60,
                'rating_count' => 12,
                'price' => 45000.00,
                'duration_days' => 7,
                'difficulty_level' => 'moderate',
                'max_participants' => 10,
                'image' => 'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?q=80&w=1200&auto=format&fit=crop',
                'start_location_name' => 'Syabrubesi',
                'start_lat' => 28.1033,
                'start_lng' => 85.3147,
                'end_location_name' => 'Syabrubesi',
                'end_lat' => 28.1033,
                'end_lng' => 85.3147,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Upper Mustang Trek',
                'description' => 'Remote desert landscapes and Tibetan-influenced culture in Mustang.',
                'trek_type' => 'adventure',
                'tags' => json_encode(['mustang','desert','tibetan']),
                'season' => json_encode(['spring','autumn']),
                'region' => 'Mustang',
                'views_count' => 350,
                'bookings_count' => 10,
                'rating_avg' => 4.50,
                'rating_count' => 8,
                'price' => 180000.00,
                'duration_days' => 14,
                'difficulty_level' => 'hard',
                'max_participants' => 8,
                'image' => 'https://images.unsplash.com/photo-1549887534-9f3c1f3c8f7a?q=80&w=1200&auto=format&fit=crop',
                'start_location_name' => 'Jomsom',
                'start_lat' => 28.7929,
                'start_lng' => 83.7383,
                'end_location_name' => 'Jomsom',
                'end_lat' => 28.7929,
                'end_lng' => 83.7383,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Muktinath Pilgrimage Trek',
                'description' => 'Spiritual route visiting temples and sacred sites near Muktinath.',
                'trek_type' => 'spiritual',
                'tags' => json_encode(['muktinath','pilgrimage','temple']),
                'season' => json_encode(['spring','autumn']),
                'region' => 'Mustang',
                'views_count' => 210,
                'bookings_count' => 6,
                'rating_avg' => 4.40,
                'rating_count' => 5,
                'price' => 60000.00,
                'duration_days' => 6,
                'difficulty_level' => 'easy',
                'max_participants' => 20,
                'image' => 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?q=80&w=1200&auto=format&fit=crop',
                'start_location_name' => 'Jomsom',
                'start_lat' => 28.7929,
                'start_lng' => 83.7383,
                'end_location_name' => 'Muktinath',
                'end_lat' => 29.0306,
                'end_lng' => 83.8964,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Chitwan Wildlife Safari',
                'description' => 'Lowland jungle with wildlife safaris, birding and Tharu cultural visits.',
                'trek_type' => 'wildlife',
                'tags' => json_encode(['chitwan','wildlife','safari']),
                'season' => json_encode(['winter','spring']),
                'region' => 'Narayani',
                'views_count' => 540,
                'bookings_count' => 25,
                'rating_avg' => 4.55,
                'rating_count' => 18,
                'price' => 30000.00,
                'duration_days' => 3,
                'difficulty_level' => 'easy',
                'max_participants' => 25,
                'image' => 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1200&auto=format&fit=crop',
                'start_location_name' => 'Sauraha',
                'start_lat' => 27.5167,
                'start_lng' => 84.4500,
                'end_location_name' => 'Sauraha',
                'end_lat' => 27.5167,
                'end_lng' => 84.4500,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Tsum Valley Trek',
                'description' => 'Remote valley with traditional villages and Himalayan scenery.',
                'trek_type' => 'village',
                'tags' => json_encode(['tsum','village','culture']),
                'season' => json_encode(['spring','autumn']),
                'region' => 'Gandaki',
                'views_count' => 130,
                'bookings_count' => 4,
                'rating_avg' => 4.35,
                'rating_count' => 3,
                'price' => 110000.00,
                'duration_days' => 12,
                'difficulty_level' => 'moderate',
                'max_participants' => 10,
                'image' => 'https://images.unsplash.com/photo-1505765058070-7b9b0f1e9d3b?q=80&w=1200&auto=format&fit=crop',
                'start_location_name' => 'Soti Khola',
                'start_lat' => 28.2600,
                'start_lng' => 84.1500,
                'end_location_name' => 'Chumling',
                'end_lat' => 28.6530,
                'end_lng' => 84.2800,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Gokyo Lakes & Historical Route',
                'description' => 'Scenic lakes, historic monasteries and traditional Sherpa villages.',
                'trek_type' => 'historical',
                'tags' => json_encode(['gokyo','lakes','monastery']),
                'season' => json_encode(['spring','autumn']),
                'region' => 'Solukhumbu',
                'views_count' => 300,
                'bookings_count' => 12,
                'rating_avg' => 4.65,
                'rating_count' => 9,
                'price' => 130000.00,
                'duration_days' => 11,
                'difficulty_level' => 'hard',
                'max_participants' => 10,
                'image' => 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?q=80&w=1200&auto=format&fit=crop',
                'start_location_name' => 'Lukla',
                'start_lat' => 27.6868,
                'start_lng' => 86.7294,
                'end_location_name' => 'Lukla',
                'end_lat' => 27.6868,
                'end_lng' => 86.7294,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Nagarkot Sunrise Walk',
                'description' => 'Short scenic walk for sunrise views over the Himalaya.',
                'trek_type' => 'scenic',
                'tags' => json_encode(['nagarkot','sunrise','short']),
                'season' => json_encode(['spring','autumn','winter']),
                'region' => 'Bagmati',
                'views_count' => 610,
                'bookings_count' => 40,
                'rating_avg' => 4.30,
                'rating_count' => 20,
                'price' => 8000.00,
                'duration_days' => 1,
                'difficulty_level' => 'easy',
                'max_participants' => 30,
                'image' => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1200&auto=format&fit=crop',
                'start_location_name' => 'Nagarkot',
                'start_lat' => 27.7061,
                'start_lng' => 85.5118,
                'end_location_name' => 'Nagarkot',
                'end_lat' => 27.7061,
                'end_lng' => 85.5118,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'name' => 'Karnali Adventure Combo',
                'description' => 'Combination of trekking and river activities in Karnali region.',
                'trek_type' => 'adventure',
                'tags' => json_encode(['karnali','rafting','remote']),
                'season' => json_encode(['spring','summer']),
                'region' => 'Karnali',
                'views_count' => 95,
                'bookings_count' => 2,
                'rating_avg' => 4.10,
                'rating_count' => 2,
                'price' => 140000.00,
                'duration_days' => 9,
                'difficulty_level' => 'hard',
                'max_participants' => 10,
                'image' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop',
                'start_location_name' => 'Surkhet',
                'start_lat' => 28.6167,
                'start_lng' => 81.6167,
                'end_location_name' => 'Surkhet',
                'end_lat' => 28.6167,
                'end_lng' => 81.6167,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('tour_packages')->insert($packages);
    }
}